num_gaussians: 50000
data_source_path: "data/warmstart_dataset/brain_cone" # path to the data (r2 style)
vol_name: "vol_prior"
model_path: "models/brain/vol_prior" # path to save/load the model checkpoints
init_mode: 'gradient' # gradient or intensity
density_thresh: 0.05 # volume density (voxel intensity) for filtering out background in initialization
density_rescale: 0.15 # Empirical density rescaling to factor in gaussian occlusions (many gaussians contributing to a voxel)
scale_min: 0.0005 # Percent of volume size
scale_max: 0.2 # Percent of volume size
eval: True