num_gaussians: 40000
data_source_path: "data/synthetic_dataset/cone_ntrain_50_angle_360/1_pepper_cone" # path to the data (r2 style)
vol_name: "vol_gt"
model_path: "models/vol_compress_tests/1_pepper_cone" # path to save/load the model checkpoints
init_mode: 'gradient' # gradient or intensity
density_thresh: 0.05 # volume density (voxel intensity) for filtering out background in initialization
density_rescale: 0.15 # Empirical density rescaling to factor in gaussian occlusions (many gaussians contributing to a voxel)
scale_min: 0.0005 # Percent of volume size
scale_max: 0.2 # Percent of volume size
eval: True