num_gaussians: 50000 # Not used in practice when init_mode is "prior",
data_source_path: "data/warmstart_dataset/brain_cone" # path to the data (r2 style)
model_path: "models/brain/recon_prior" # path to save/load the model checkpoints
init_mode: 'prior' # precomputed or gradient or intensity or prior
prior_path: "models/brain/vol_prior/point_cloud/step_10/point_cloud.pickle" # Set path to specific point cloud if "prior" mode used for initialization.
density_thresh: 0.05 # volume density (voxel intensity) for filtering out background in initialization
density_rescale: 0.15 # Empirical density rescaling to factor in gaussian occlusions (many gaussians contributing to a voxel)
scale_min: 0.0005 # Percent of volume size
scale_max: 0.5 # Percent of volume size
eval: True
