steps: 500
position_lr_init: 0.005
position_lr_final: 0.001
position_lr_max_steps: 1.0 #percentage of total steps
density_lr_init: 0.01
density_lr_final: 0.005
density_lr_max_steps: 1.0 #percentage of total steps
scaling_lr_init: 0.01
scaling_lr_final: 0.005
scaling_lr_max_steps: 1.0 #percentage of total steps
rotation_lr_init: 0.005
rotation_lr_final: 0.001
rotation_lr_max_steps: 1.0 #percentage of total steps
lambda_dssim: 0.25 # weight for the DSSIM loss 
lambda_tv: 0.0 # weight for the TV loss

densify_gaussians: False # Probably don't use for volume fitting, doesn't seem to help
density_min_threshold: 0.0001
densification_interval: 100
densify_from_step: 100
densify_until_step_percent: 0.5 # percentage of total steps
densify_grad_threshold: 5.0e-5
densify_scale_threshold: 0.1  # percent of volume size
max_screen_size: null
max_scale: null  # percent of volume size
max_num_gaussians: 1.1  # multiplier relative to model.num_gaussians

ssim3d_early_stop: false
ssim3d_early_stop_threshold: 0.0
training_time_limit_seconds: 0.0

# Bit precision
quantize:              True # Enable bit precision control of Gaussian parameters
pos_bits:              16 # Bit precision of individual coordinate dimension
scale_bits:            16 # Bit precision of individual scale dimension
rot_bits:              16 # Bit precision of Gaussian orientation angle
feat_bits:             16 # Bit precision of individual feature dimension
