steps: 20000
position_lr_init: 0.0002
position_lr_final: 0.00002
position_lr_max_steps: 1.0 #percentage of total steps
density_lr_init: 0.01
density_lr_final: 0.001
density_lr_max_steps: 1.0 #percentage of total steps
scaling_lr_init: 0.005
scaling_lr_final: 0.0005
scaling_lr_max_steps: 1.0 #percentage of total steps
rotation_lr_init: 0.001
rotation_lr_final: 0.0001
rotation_lr_max_steps: 1.0 #percentage of total steps
lambda_dssim: 0.3 # weight for the DSSIM loss
lambda_tv: 0.05 # weight for the TV loss
tv_vol_size: 32 # volume sample size (cube width) for computing the TV loss

densify_gaussians: True
density_min_threshold: 0.0001
densification_interval: 500
densify_from_step: 100 # Static number
densify_until_step_percent: 0.5 # percentage of total steps
densify_grad_threshold: 5.0e-5
densify_scale_threshold: 0.1  # percent of volume size
max_screen_size: null
max_scale: null  # percent of volume size
max_num_gaussians: 1.1  # multiplier relative to model.num_gaussians (e.g., 1.1 = 110%)

ssim3d_early_stop: true
ssim3d_early_stop_threshold: 0.9
training_time_limit_seconds: 0.0 # If > 0, stop training after this many seconds have elapsed
